2019-12-06 12:01:19,699 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:45]
2019-12-06 12:10:36,671 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:45]
2019-12-06 12:35:11,441 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:45]
2019-12-06 12:51:09,782 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:45]
2019-12-06 13:31:57,050 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:48]
2019-12-06 13:32:33,090 ERROR: Exception on /reset_password_request [POST] [in c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Chirag Kushwaha\Desktop\microblog\app\routes.py", line 155, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Chirag Kushwaha\Desktop\microblog\app\email.py", line 19, in send_password_reset_email
    user=user, token=token))
  File "C:\Users\Chirag Kushwaha\Desktop\microblog\app\email.py", line 9, in send_email
    mail.send(msg)
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "C:\Users\Chirag Kushwaha\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Users\Chirag Kushwaha\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\Chirag Kushwaha\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 307, in _get_socket
    self.source_address)
  File "C:\Users\Chirag Kushwaha\AppData\Local\Programs\Python\Python37\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\Chirag Kushwaha\AppData\Local\Programs\Python\Python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
2019-12-06 17:42:33,366 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:50]
2019-12-06 17:46:09,268 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:50]
2019-12-06 19:21:10,304 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:50]
2019-12-06 19:29:16,134 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:50]
2019-12-06 19:30:49,625 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:50]
2019-12-06 21:11:18,133 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:19:50,894 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:20:58,223 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:21:32,960 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:21:37,807 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:22:26,243 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:24:40,752 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:30:09,966 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:30:34,238 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:30:54,084 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:31:37,998 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:33:45,050 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:35:43,540 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:45:55,393 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:47:45,710 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:48:18,922 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:50:28,760 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:51:03,306 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:51:14,785 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:54:32,141 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:55:13,293 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:55:25,136 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-06 21:55:33,171 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 04:34:06,937 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 04:34:16,851 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 04:41:19,993 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 04:41:54,260 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 05:29:43,529 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 05:32:52,261 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 05:34:10,587 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 05:38:50,462 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 05:56:12,296 INFO: Microblog startup [in C:\Users\Chirag Kushwaha\Desktop\microblog\app\__init__.py:52]
2019-12-07 06:00:00,330 ERROR: Exception on /translate [POST] [in c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\chirag~1\desktop\microb~1\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Chirag Kushwaha\Desktop\microblog\app\routes.py", line 202, in translate_text
    request.form['dest_language'])['text'][0]})
TypeError: string indices must be integers
